version: '3.8'

services:
  app:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    command: python app.py
